const calorieProteinMap = new Map();

// Add items and their calorie/protein information for 100g
calorieProteinMap.set('panner',{calories:265,proteins:18});
calorieProteinMap.set('rice', { calories: 130, proteins: 2.7 });
calorieProteinMap.set('dal', { calories: 160, proteins: 7 });
calorieProteinMap.set('roti', { calories: 85, proteins: 2.5 });
calorieProteinMap.set('chicken', { calories: 165, proteins: 31 });
calorieProteinMap.set('potato', { calories: 77, proteins: 2 });
calorieProteinMap.set('bread', { calories: 265, proteins: 9.5 });
calorieProteinMap.set('egg', { calories: 143, proteins: 13 });
calorieProteinMap.set('milk', { calories: 42, proteins: 3.4 });
calorieProteinMap.set('banana', { calories: 89, proteins: 1.1 });
calorieProteinMap.set('apple', { calories: 52, proteins: 0.3 });
calorieProteinMap.set('orange', { calories: 43, proteins: 1 });
calorieProteinMap.set('carrot', { calories: 41, proteins: 0.9 });
calorieProteinMap.set('broccoli', { calories: 55, proteins: 3.7 });
calorieProteinMap.set('lettuce', { calories: 5, proteins: 0.5 });
calorieProteinMap.set('tomato', { calories: 18, proteins: 0.9 });
calorieProteinMap.set('cucumber', { calories: 16, proteins: 0.7 });
calorieProteinMap.set('onion', { calories: 40, proteins: 1.1 });
calorieProteinMap.set('garlic', { calories: 149, proteins: 6.4 });
calorieProteinMap.set('ginger', { calories: 80, proteins: 1.8 });
calorieProteinMap.set('mushroom', { calories: 80, proteins: 3});
calorieProteinMap.set('fish', { calories: 150, proteins: 18});
calorieProteinMap.set('curd', { calories: 98, proteins: 11});
calorieProteinMap.set('peanut butter', { calories: 588, proteins: 25});
calorieProteinMap.set('peanut', { calories: 567, proteins: 25});
calorieProteinMap.set('almond', { calories: 579, proteins: 21});
calorieProteinMap.set('cashew', { calories: 553, proteins: 18});
calorieProteinMap.set('walnut', { calories: 654, proteins: 15});
calorieProteinMap.set('raisin', { calories: 299, proteins: 3});
calorieProteinMap.set('dates', { calories: 282, proteins: 2});
calorieProteinMap.set('pistachio', { calories: 562, proteins: 20});
calorieProteinMap.set('soya', { calories: 446, proteins: 36});
calorieProteinMap.set('oats', { calories: 389, proteins: 17});
calorieProteinMap.set('corn', { calories: 342, proteins: 12});
calorieProteinMap.set('peas', { calories: 81, proteins: 5});
calorieProteinMap.set('kidney beans', { calories: 127, proteins: 9});
calorieProteinMap.set('chickpeas', { calories: 164, proteins: 9});
calorieProteinMap.set('lentils', { calories: 116, proteins: 9});
calorieProteinMap.set('soybean', { calories: 446, proteins: 36});
calorieProteinMap.set('tofu', { calories: 76, proteins: 8});
calorieProteinMap.set('white bread', { calories: 265, proteins: 9.5});
calorieProteinMap.set('brown bread', { calories: 246, proteins: 8.7});
calorieProteinMap.set('pasta', { calories: 131, proteins: 5});
calorieProteinMap.set('butter', { calories: 717, proteins: 0.9});
calorieProteinMap.set('cheese', { calories: 402, proteins: 25});
calorieProteinMap.set('yogurt', { calories: 59, proteins: 3.5});
calorieProteinMap.set('ice cream', { calories: 207, proteins: 3.5});
calorieProteinMap.set('chocolate', { calories: 546, proteins: 6});
calorieProteinMap.set('cake', { calories: 237, proteins: 3});
calorieProteinMap.set('pizza', { calories: 266, proteins: 11});
calorieProteinMap.set('burger', { calories: 295, proteins: 13});
calorieProteinMap.set('fries', { calories: 312, proteins: 3.5});
calorieProteinMap.set('chips', { calories: 536, proteins: 6});
calorieProteinMap.set('coke', { calories: 140, proteins: 0});
calorieProteinMap.set('pepsi', { calories: 150, proteins: 0});
calorieProteinMap.set('sprite', { calories: 140, proteins: 0});
calorieProteinMap.set('fanta', { calories: 140, proteins: 0});
calorieProteinMap.set('red bull', { calories: 45, proteins: 0});
calorieProteinMap.set('coffee', { calories: 1, proteins: 0.3});
calorieProteinMap.set('tea', { calories: 1, proteins: 0.3});
calorieProteinMap.set('beer', { calories: 43, proteins: 0.5});
calorieProteinMap.set('wine', { calories: 83, proteins: 0.1});
calorieProteinMap.set('vodka', { calories: 231, proteins: 0});
calorieProteinMap.set('whiskey', { calories: 222, proteins: 0});
calorieProteinMap.set('rum', { calories: 231, proteins: 0});
calorieProteinMap.set('gin', { calories: 263, proteins: 0});
calorieProteinMap.set('tequila', { calories: 231, proteins: 0});
calorieProteinMap.set('potato pave', { calories: 213, proteins: 2.5});
calorieProteinMap.set('sweet potato', { calories: 86, proteins: 1.6});
calorieProteinMap.set('avocado', { calories: 160, proteins: 2});
calorieProteinMap.set('pumpkin', { calories: 26, proteins: 1});
calorieProteinMap.set('spinach', { calories: 23, proteins: 2.9});
calorieProteinMap.set('duck', { calories: 337, proteins: 16});
calorieProteinMap.set('turkey', { calories: 189, proteins: 29});
calorieProteinMap.set('lamb', { calories: 294, proteins: 25});
calorieProteinMap.set('pork', { calories: 242, proteins: 26});
calorieProteinMap.set('beef', { calories: 250, proteins: 26});
calorieProteinMap.set('bacon', { calories: 541, proteins: 37});
calorieProteinMap.set('sausage', { calories: 301, proteins: 13});
calorieProteinMap.set('ham', { calories: 145, proteins: 18});
calorieProteinMap.set('salmon', { calories: 208, proteins: 20});
calorieProteinMap.set('tuna', { calories: 116, proteins: 26});
calorieProteinMap.set('cod', { calories: 82, proteins: 18});
calorieProteinMap.set('haddock', { calories: 116, proteins: 26});
calorieProteinMap.set('herring', { calories: 158, proteins: 18});
calorieProteinMap.set('trout', { calories: 119, proteins: 20});
calorieProteinMap.set('sardine', { calories: 208, proteins: 20});
calorieProteinMap.set('pudding', { calories: 171, proteins: 3}); 
calorieProteinMap.set('custard', { calories: 153, proteins: 3});
calorieProteinMap.set('jelly', { calories: 62, proteins: 0});
calorieProteinMap.set('mousse', { calories: 171, proteins: 3});
calorieProteinMap.set('crossiant', { calories: 406, proteins: 8});
calorieProteinMap.set('bagel', { calories: 289, proteins: 11});
calorieProteinMap.set('hot dogs', { calories: 296, proteins: 11});
calorieProteinMap.set('donuts', { calories: 452, proteins: 5});
calorieProteinMap.set('muffins', { calories: 265, proteins: 5});
calorieProteinMap.set('waffles', { calories: 291, proteins: 7});
calorieProteinMap.set('pancakes', { calories: 227, proteins: 6});
calorieProteinMap.set('macaroni', { calories: 157, proteins: 5});
calorieProteinMap.set('noodles', { calories: 138, proteins: 5});
calorieProteinMap.set('spaghetti', { calories: 157, proteins: 5});
calorieProteinMap.set('lasagna', { calories: 157, proteins: 5});
calorieProteinMap.set('cereal', { calories: 379, proteins: 8});
calorieProteinMap.set('granola', { calories: 489, proteins: 10});
calorieProteinMap.set('nuggest', { calories: 287, proteins: 14});
calorieProteinMap.set('chicken wings', { calories: 290, proteins: 17});
calorieProteinMap.set('chicken tenders', { calories: 290, proteins: 17});
calorieProteinMap.set('chicken nuggets', { calories: 287, proteins: 14});
calorieProteinMap.set('chicken drumsticks', { calories: 290, proteins: 17});
calorieProteinMap.set('chicken thighs', { calories: 290, proteins: 17});
calorieProteinMap.set('chicken breast', { calories: 165, proteins: 31});
calorieProteinMap.set('chicken legs', { calories: 290, proteins: 17});
calorieProteinMap.set('chicken roast', { calories: 165, proteins: 31});
calorieProteinMap.set('chicken curry', { calories: 165, proteins: 31});
calorieProteinMap.set('chicken biryani', { calories: 165, proteins: 31});
calorieProteinMap.set('chicken tikka', { calories: 165, proteins: 31});
calorieProteinMap.set('chicken korma', { calories: 165, proteins: 31});
calorieProteinMap.set('chicken butter masala', { calories: 165, proteins: 31});
calorieProteinMap.set('chicken lollipop', { calories: 165, proteins: 31});
calorieProteinMap.set('chicken soup', { calories: 165, proteins: 31});
calorieProteinMap.set('chicken salad', { calories: 165, proteins: 31});
calorieProteinMap.set('chicken sandwich', { calories: 165, proteins: 31});
calorieProteinMap.set('chicken burger', { calories: 165, proteins: 31});

// Add more items

export default calorieProteinMap;
